In [ ]:
import nltk
nltk.download()

In [ ]:
#Read the raw data
#remove punctuations from data
#remove punctuations from data
#remove stopwords from data
#Handle Tokenization
 #apply lemmitization

In [3]:
import nltk
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
import string

In [4]:
stopwords = nltk.corpus.stopwords.words('English')
ps = nltk.PorterStemmer()

In [5]:
spam=pd.read_csv("C:\\Users\\user\\Downloads\\SpamData.tsv ",delimiter="\t")
spam.columns=['labels','text']

In [6]:
spam.head()

labels                                               text
0   spam  Free entry in 2 a wkly comp to win FA Cup fina...
1    ham  Nah I don't think he goes to usf, he lives aro...
2    ham  Even my brother is not like to speak with me. ...
3    ham                I HAVE A DATE ON SUNDAY WITH WILL!!
4    ham  As per your request 'Melle Melle (Oru Minnamin...

In [7]:
def count_punct(text):
    count = sum([1 for char in text if char in string.punctuation])
    return round(count/(len(text) - text.count(" ")) ,3)*100

In [8]:
x=spam.iloc[:,1].values

In [9]:
spam['len'] = spam['text'].apply(lambda x:len(x) - x.count(" "))
spam['punct%'] = spam['text'].apply(lambda x:count_punct(x))
spam.head()

labels                                               text  len  punct%
0   spam  Free entry in 2 a wkly comp to win FA Cup fina...  128     4.7
1    ham  Nah I don't think he goes to usf, he lives aro...   49     4.1
2    ham  Even my brother is not like to speak with me. ...   62     3.2
3    ham                I HAVE A DATE ON SUNDAY WITH WILL!!   28     7.1
4    ham  As per your request 'Melle Melle (Oru Minnamin...  135     4.4

In [10]:
def clean_text(text):
    text = "".join([word.lower() for word in text if word not in string.punctuation])
    tokens = re.split('\W+',text)
    text = [ps.stem(word) for word in tokens if word not in stopwords]
    return text

In [11]:
import numpy as np

In [12]:
x=np.array(x)

In [13]:
x

array(["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       "Nah I don't think he goes to usf, he lives around here though",
       'Even my brother is not like to speak with me. They treat me like aids patent.',
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [14]:
### bag of words#
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv=CountVectorizer(max_features=1500)

In [16]:
x=cv.fit_transform(x).toarray()

In [17]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
cv.get_feature_names()

['00',
 '000',
 '02',
 '03',
 '04',
 '06',
 '0800',
 '08000839402',
 '08000930705',
 '0870',
 '08712460324',
 '08718720201',
 '10',
 '100',
 '1000',
 '10am',
 '10p',
 '11',
 '11mths',
 '12',
 '12hrs',
 '1327',
 '150',
 '150p',
 '150ppm',
 '16',
 '18',
 '1st',
 '20',
 '200',
 '2000',
 '2003',
 '2004',
 '20p',
 '25',
 '250',
 '25p',
 '2day',
 '2lands',
 '2nd',
 '2nite',
 '30',
 '3030',
 '350',
 '36504',
 '3g',
 '400',
 '4u',
 '50',
 '500',
 '5000',
 '50p',
 '5wb',
 '5we',
 '62468',
 '750',
 '7pm',
 '800',
 '8007',
 '82277',
 '85023',
 '86688',
 '87066',
 '87077',
 '8th',
 '900',
 'abiola',
 'able',
 'about',
 'abt',
 'ac',
 'accept',
 'access',
 'account',
 'across',
 'actually',
 'add',
 'address',
 'admirer',
 'advance',
 'aft',
 'after',
 'afternoon',
 'again',
 'against',
 'age',
 'age16',
 'ago',
 'ah',
 'aha',
 'ahead',
 'aight',
 'al',
 'alex',
 'all',
 'almost',
 'alone',
 'already',
 'alright',
 'alrite',
 'also',
 'always',
 'am',
 'amp',
 'an',
 'and',
 'angry',
 'another',
 '

In [29]:
pd.DataFrame(x,columns=cv.get_feature_names())

00  000  02  03  04  06  0800  08000839402  08000930705  0870  ...  yo  \
0      0    0   0   0   0   0     0            0            0     0  ...   0   
1      0    0   0   0   0   0     0            0            0     0  ...   0   
2      0    0   0   0   0   0     0            0            0     0  ...   0   
3      0    0   0   0   0   0     0            0            0     0  ...   0   
4      0    0   0   0   0   0     0            0            0     0  ...   0   
...   ..  ...  ..  ..  ..  ..   ...          ...          ...   ...  ...  ..   
5562   0    0   0   0   0   0     0            0            0     0  ...   0   
5563   0    0   0   0   0   0     0            0            0     0  ...   0   
5564   0    0   0   0   0   0     0            0            0     0  ...   0   
5565   0    0   0   0   0   0     0            0            0     0  ...   0   
5566   0    0   0   0   0   0     0            0            0     0  ...   0   

      yoga  you  your  yours  yourself  yr  yrs  yup  zed  
0        0    0     0      0         0   0    0    0    0  
1        0    0     0      0         0   0    0    0    0  
2        0    0     0      0         0   0    0    0    0  
3        0    0     0      0         0   0    0    0    0  
4        0    0     3      0         0   0    0    0    0  
...    ...  ...   ...    ...       ...  ..  ...  ...  ...  
5562     0    0     0      0         0   0    0    0    0  
5563     0    0     0      0         0   0    0    0    0  
5564     0    0     0      0         0   0    0    0    0  
5565     0    0     0      0         0   0    0    0    0  
5566     0    0     0      0         0   0    0    0    0  

[5567 rows x 1500 columns]

In [145]:
#calculate TFIDF(converting data into vector format to apply ML or DL
#consider TFIDF as new dataset
#consider the input variable(TFIDF) and output variable from Raw data

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [32]:
tfidf_vec=TfidfVectorizer(max_features=1510)

In [33]:
x_tfidf=tfidf_vec.fit_transform(spam['text']).toarray()

In [34]:
x_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
tfidf_vec.get_feature_names()

['00',
 '000',
 '02',
 '03',
 '04',
 '06',
 '0800',
 '08000839402',
 '08000930705',
 '0870',
 '08712460324',
 '08718720201',
 '10',
 '100',
 '1000',
 '10am',
 '10p',
 '11',
 '11mths',
 '12',
 '12hrs',
 '1327',
 '150',
 '150p',
 '150ppm',
 '16',
 '18',
 '1st',
 '20',
 '200',
 '2000',
 '2003',
 '2004',
 '20p',
 '25',
 '250',
 '25p',
 '2day',
 '2lands',
 '2nd',
 '2nite',
 '30',
 '3030',
 '350',
 '36504',
 '3g',
 '400',
 '4u',
 '50',
 '500',
 '5000',
 '50p',
 '5wb',
 '5we',
 '62468',
 '750',
 '7pm',
 '800',
 '8007',
 '82277',
 '85023',
 '86688',
 '87066',
 '87077',
 '8th',
 '900',
 'abiola',
 'able',
 'about',
 'abt',
 'ac',
 'accept',
 'access',
 'account',
 'across',
 'actually',
 'add',
 'address',
 'admirer',
 'advance',
 'aft',
 'after',
 'afternoon',
 'again',
 'against',
 'age',
 'age16',
 'ago',
 'ah',
 'aha',
 'ahead',
 'aight',
 'al',
 'alex',
 'all',
 'almost',
 'alone',
 'already',
 'alright',
 'alrite',
 'also',
 'always',
 'am',
 'amp',
 'an',
 'and',
 'angry',
 'another',
 '

In [37]:
pd.DataFrame(x_tfidf,columns=tfidf_vec.get_feature_names())

00  000   02   03   04   06  0800  08000839402  08000930705  0870  ...  \
0     0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   
1     0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   
2     0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   
3     0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   
4     0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   
...   ...  ...  ...  ...  ...  ...   ...          ...          ...   ...  ...   
5562  0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   
5563  0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   
5564  0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   
5565  0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   
5566  0.0  0.0  0.0  0.0  0.0  0.0   0.0          0.0          0.0   0.0  ...   

       yo  yoga  you      your  yours  yourself   yr  yrs  yup  zed  
0     0.0   0.0  0.0  0.000000    0.0       0.0  0.0  0.0  0.0  0.0  
1     0.0   0.0  0.0  0.000000    0.0       0.0  0.0  0.0  0.0  0.0  
2     0.0   0.0  0.0  0.000000    0.0       0.0  0.0  0.0  0.0  0.0  
3     0.0   0.0  0.0  0.000000    0.0       0.0  0.0  0.0  0.0  0.0  
4     0.0   0.0  0.0  0.302603    0.0       0.0  0.0  0.0  0.0  0.0  
...   ...   ...  ...       ...    ...       ...  ...  ...  ...  ...  
5562  0.0   0.0  0.0  0.000000    0.0       0.0  0.0  0.0  0.0  0.0  
5563  0.0   0.0  0.0  0.000000    0.0       0.0  0.0  0.0  0.0  0.0  
5564  0.0   0.0  0.0  0.000000    0.0       0.0  0.0  0.0  0.0  0.0  
5565  0.0   0.0  0.0  0.000000    0.0       0.0  0.0  0.0  0.0  0.0  
5566  0.0   0.0  0.0  0.000000    0.0       0.0  0.0  0.0  0.0  0.0  

[5567 rows x 1510 columns]

In [39]:
print(x_tfidf.shape)

(5567, 1510)


In [140]:
y=spam['len']

TypeError: string indices must be integers

In [87]:
y

0       128
1        49
2        62
3        28
4       135
       ... 
5562    131
5563     29
5564     48
5565    100
5566     21
Name: len, Length: 5567, dtype: int64

In [51]:
#split the data into Training and Testing

In [88]:
from sklearn.metrics import precision_recall_fscore_support as score

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
x_train,x_test,y_train,y_test = train_test_split(x_tfidf,y,test_size=0.2,random_state=42)

In [91]:
x_train.shape

(4453, 1510)

In [141]:
y_train.shape

(4453,)

In [92]:
x_test.shape

(1114, 1510)

In [93]:
import numpy as np
import pandas as pd

In [94]:
import keras
import tensorflow

In [95]:
##Building the NN model#
from keras.models import Sequential
from keras.layers import Dense
model=Sequential()

In [96]:
##Add input layer#
x_train.shape[1]
model.add(Dense(input_dim = x_train.shape[1],kernel_initializer="random_uniform",activation="relu",units=10))

In [97]:
##Add hiddenlayer#
model.add(Dense(kernel_initializer="random_uniform",activation="relu",units=6))

In [98]:
#Add output layer#
model.add(Dense(kernel_initializer="random_uniform",activation="sigmoid",units=1))

In [99]:
##Compile the model#
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 10)                15110     
_________________________________________________________________
dense_7 (Dense)              (None, 6)                 66        
_________________________________________________________________
dense_8 (Dense)              (None, 1)                 7         
Total params: 15,183
Trainable params: 15,183
Non-trainable params: 0
_________________________________________________________________


In [143]:
model.fit(x_train,y_train,batch_size=32,epochs=5)

Epoch 1/5
140/140 [==============================] - 3s 3ms/step - loss: -7.4522 - accuracy: 0.0000e+00
Epoch 2/5
140/140 [==============================] - 0s 2ms/step - loss: -309.0831 - accuracy: 0.0000e+00
Epoch 3/5
140/140 [==============================] - 0s 2ms/step - loss: -1977.4136 - accuracy: 0.0000e+00
Epoch 4/5
140/140 [==============================] - 0s 2ms/step - loss: -6629.8969 - accuracy: 0.0000e+00
Epoch 5/5
140/140 [==============================] - 0s 2ms/step - loss: -15075.4144 - accuracy: 0.0000e+00


In [100]:
#prediction#
y_pred=model.predict_classes(x_test)

C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [101]:
y_pred

array([[1],
       [1],
       [1],
       ...,
       [0],
       [1],
       [1]])

In [144]:
from sklearn.metrics import accuracy_score

In [145]:
accuracy_score(y_test,y_pred)

0.0

In [146]:
###new prediction#
my_text="I HAVE A DATE ON SUNDAY WITH WILL!!"

In [147]:
my_text=np.array([my_text])

In [148]:
my_text

array(['I HAVE A DATE ON SUNDAY WITH WILL!!'], dtype='<U35')

In [165]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [166]:
tfidf=TfidfVectorizer(max_features=5)

In [164]:
my_text

array([[0.40824829, 0.40824829, 0.40824829, 0.40824829, 0.40824829,
        0.40824829]])

In [167]:
my_text=tfidf.fit_transform(my_text).toarray()

AttributeError: 'numpy.ndarray' object has no attribute 'lower'

In [152]:
my_text

array([[0.40824829, 0.40824829, 0.40824829, 0.40824829, 0.40824829,
        0.40824829]])

In [153]:
my_text.shape

(1, 6)

In [155]:
model.predict_classes(my_text)

ValueError: in user code:

    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1478 predict_function  *
        return step_function(self, iterator)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1468 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1461 run_step  **
        outputs = model.predict_step(data)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1434 predict_step
        return self(x, training=False)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\input_spec.py:255 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer sequential_2 is incompatible with the layer: expected axis -1 of input shape to have value 1510 but received input with shape (None, 6)


In [170]:
model.predict_classes(my_text)

ValueError: in user code:

    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1478 predict_function  *
        return step_function(self, iterator)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1468 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:1259 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:2730 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:3417 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1461 run_step  **
        outputs = model.predict_step(data)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1434 predict_step
        return self(x, training=False)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\base_layer.py:998 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\input_spec.py:255 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer sequential_2 is incompatible with the layer: expected axis -1 of input shape to have value 1510 but received input with shape (None, 6)
